version: '3.3'
services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    environment:
      - MYSQL_DATABASE=dockerapp
      - MYSQL_ROOT_PASSWORD=112358
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      #Corre todos los archivos .sql que se encuentren en esa carpeta
      - ./dbquery:/docker-entrypoint-initdb.d/
      - db:/data/db
  appi:
    container_name: appi
    build: ./appi
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      #- ./appi:/usr/src/app
      - ./appi:/app
    #Solo se iniciará cuando mysql se inicie
    depends_on:
      - mysqldb
    #command: ["wait-for-it", "mysqldb:3306", "--", "node",  "src/index.js"]
    command: sh -c "/wait" && npm run start
    environment:
      - WAIT_HOSTS=mysqldb:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30

volumes:
  db:
    driver: local
