version: '3.9'
services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    environment:
      - MYSQL_DATABASE=dockerapp
      - MYSQL_ROOT_PASSWORD=112358
    ports:
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      #Corre todos los archivos .sql que se encuentren en esa carpeta
      - ./dbquery:/docker-entrypoint-initdb.d/
      - db:/data/db
  appi:
    container_name: appi
    build: ./appi
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - ./appi:/usr/src/app
    #Solo se iniciará cuando mysql se inicie
    depends_on:
      - mysqldb

volumes:
  db:
    driver: local
